<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HAIDAR" failures="1" tests="3" name="org.haidar.cucumberbdd.TestNGRunner" time="16.906" errors="0" timestamp="2025-03-29T23:35:32 IST" skipped="0">
  <testcase classname="org.haidar.cucumberbdd.TestNGRunner" name="runScenario" time="5.555"/>
  <testcase classname="org.haidar.cucumberbdd.TestNGRunner" name="runScenario" time="5.795"/>
  <testcase classname="org.haidar.cucumberbdd.TestNGRunner" name="runScenario" time="5.556">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at org.junit.Assert.assertFalse(Assert.java:75)
at org.haidar.cucumberbdd.StepDefinitions.i_click_the_login_button(StepDefinitions.java:89)
at âœ½.I click the login button(file:///D:/EclipseSoftware/cucumberbddwithTestNG/src/test/resources/featuresToBeRunInParallel/login.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- org.haidar.cucumberbdd.TestNGRunner -->
